### ISSUE TITLE
Docker plugin is not showing any releases

### ISSUE THREAD

**Issue by vsilverman** [jenkins-infra/plugin-site#282] opened 2020-06-23 21:59 UTC
Problem with the [Docker](https://plugins.jenkins.io/docker-plugin) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

TODO: Releases tab doesn't contain any info

## Screenshots 

 TODO: Add screenshots if possible 

## Possible Solution 

 

N/A

**Comment by halkeye** [comment] 2020-06-23 22:39
I got confused with all the Todo notes still in the bug report. Your supposed to fill them out.

Yes. Right now the backend and frontend only support GitHub releases. If docker plugin is using GitHub releases and it's still broken it's a bug I'll have to look into.

I'll try to follow up after work

**Comment by halkeye** [comment] 2020-06-24 03:10
Okay, looks like https://plugins.jenkins.io/api/plugin/docker-plugin/releases returns no results, and looking at the repo there's a changelog.md, so its a duplicate of #263, so closing this one.

**Closed as completed by halkeye** 2020-06-24 03:10 UTC
Labels: duplicate
