### ISSUE TITLE
docker-build-step page - provide the content source for Releases info

### ISSUE THREAD

**Issue by vsilverman** [jenkins-infra/plugin-site#494] opened 2020-11-23 18:59 UTC
Empty content for docker-build-step [Releases](https://plugins.jenkins.io/docker-build-step/#releases)

![image](https://user-images.githubusercontent.com/2159948/100003393-de135100-2d7a-11eb-90ca-3e91483170bf.png)

**Comment by halkeye** [comment] 2020-11-23 19:00
duplicate of #480

**Closed as completed by halkeye** 2020-11-23 19:00 UTC
