### ISSUE TITLE
Plugin results page does not sort based on selected filter

### ISSUE THREAD

**Issue by kmartens27** [jenkins-infra/plugin-site#1261] opened 2023-01-06 14:33 UTC
Follow up for [WEBSITE-783](https://issues.jenkins.io/browse/WEBSITE-763)

Sorting the plugin results does not work. Regardless of the filter selected, the page does not update or re-sort the plugins displayed.

![Screen Shot 2023-01-06 at 9 30 44 AM](https://user-images.githubusercontent.com/99040580/211032424-d4b48961-35c7-49d9-9457-02d94cb8c424.png)

![Screen Shot 2023-01-06 at 9 28 16 AM](https://user-images.githubusercontent.com/99040580/211032460-61dae75f-5db2-41f8-8df3-b016fa5f6eec.png)
![Screen Shot 2023-01-06 at 9 28 34 AM](https://user-images.githubusercontent.com/99040580/211032463-f6164e7d-b4ff-49a7-b9b6-8f2438deb221.png)

# Possible Solution

Would it be possible to review and update the plugin filtering/results so that it is updated as expected?

**Comment by zbynek** [comment] 2023-01-06 14:58
Duplicate of #632

**Closed as completed by zbynek** 2023-01-06 14:58 UTC
