### ISSUE TITLE
CloudBees Docker Custom Build Environment page - provide the content source for Releases info

### ISSUE THREAD

**Issue by vsilverman** [jenkins-infra/plugin-site#493] opened 2020-11-23 18:51 UTC
Empty content for docker-custom-build-environment [Releases](https://plugins.jenkins.io/docker-custom-build-environment/#releases)

![image](https://user-images.githubusercontent.com/2159948/100002623-b2439b80-2d79-11eb-9fb0-1684fa0a2f0a.png)

**Comment by halkeye** [comment] 2020-11-23 18:58
duplicate of #480 
plugin-site-api so far only supports pulling releases from github releases api and https://github.com/jenkinsci/docker-custom-build-environment-plugin/releases has 0 published releases.

**Closed as completed by halkeye** 2020-11-23 18:58 UTC
