### ISSUE TITLE
#releases tab does not hydrate correctly

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/plugin-site#1253] opened 2022-12-02 21:26 UTC
Accessing the releases tab directly, e.g. by clicking https://plugins.jenkins.io/matrix-auth/#releases results in broken presentation (the first item does not have the border and background color, and the margin between entries is very small).

According to @halkeye in IRC,

> looks like its not hydrating properly, if you switch tabs and back it seems to be fine

which I can confirm: Going to https://plugins.jenkins.io/matrix-auth/ then clicking "Releases" results in a correct looking UI.

FWIW it also looks like https://plugins.jenkins.io/matrix-auth/#dependencies appears different depending on how you navigated there, but it's mostly minor margin and font size differences.

**Comment by lemeurherve** [comment] 2022-12-02 21:54
Duplicate of #1240

**Closed as completed** 2022-12-03 08:56 UTC
