### ISSUE TITLE
Docker page - provide the content source for Releases info

### ISSUE THREAD

**Issue by vsilverman** [jenkins-infra/plugin-site#480] opened 2020-11-16 21:58 UTC
Empty content for docker-plugin [Releases](https://plugins.jenkins.io/docker-plugin/#releases)

![image](https://user-images.githubusercontent.com/2159948/99313026-b9b3f380-2813-11eb-8f4f-301b5b76723b.png)

**Comment by zbynek** [comment] 2020-11-16 22:02
This can be either fixed by Docker plugin switching to GitHub releases (@pjdarton looped) or plugin site implementing
https://github.com/jenkins-infra/plugin-site/issues/263 to grab the info from changelog. Maybe we should close this issue in favor of #263 .

**Comment by pjdarton** [comment] 2020-11-16 23:35
GitHub releases are something I've heard of ... but know nothing about (other than the years-old bug where GH can't distinguish between releases and tags).
I'm quite happy to switch to GH releases, if someone can ensure my ignorance is no longer a barrier ;-)

... and given that a recent Jenkins release removed agent.jar's support for the -slaveLog argument, I'm going to have to do a new release fairly soon (next week maybe as I'm not working this week) so "now" would be a good time to do that switch.

**Comment by halkeye** [comment] 2020-11-16 23:38
My suggestion is to use release drafter:

https://github.com/jenkinsci/archetypes/blob/master/common-files/.github/release-drafter.yml
https://github.com/jenkinsci/archetypes/blob/master/common-files/.github/workflows/release-drafter.yml

Then any PR you merge will get appended to draft release. and if you label the PRs, you'll get categories too.

With out that, you can create a new release and fill in fields, or edit a tag and publish as a release (so you can backfill as necessary).

**Comment by vsilverman** [comment] 2020-11-18 23:36
While fixing this issue it may be useful to make sure that [Release versions are in sync](https://github.com/jenkinsci/docker/issues/1030)

**Comment by halkeye** [comment] 2020-11-19 00:01
In sync with what? Docker? The plugins don't have docker releases.

**Comment by vsilverman** [comment] 2020-11-19 00:54
Oh, yes, exactly right, mixed up Jenkins docker-plugin with Jenkins docker release. Those issues are unrelated, will remove my comment

**Comment by pjdarton** [comment] 2020-11-23 10:54
So, from my point of view, while I generally approve of "automating everything", I think that [XKCD is bang on the money here](https://xkcd.com/1205/) and one should take a more balanced view.
It doesn't take me long to update the CHANGELOG.md file, whereas the time taken to fully learn all the ins and outs of an automated process (especially the time taken to backfill old releases) would take me a lot of time that I don't have to spare.

If I was starting a brand new plugin so there was "nothing to lose", or if I was kicking out releases for things on a daily basis then, sure, it'd be worthwhile mastering that automated thing to save me some time, but I don't see the benefit right now - sometimes a low-tech option is best ("keep it simple") and I think this is one of those times.
(If I was working with Jenkins experts on a daily basis and able to lean over a desk-partition to ask "Oi! How does this bit work?" 10 times a day, then it'd probably be different, but as-is the cost of learning new stuff is non-trivial)

...so I would, instead, advocate having the plugin site being more flexible in where it gets its data from, e.g. #263 as that'll fix the issue for far more than just the docker-plugin.

**Comment by halkeye** [comment] 2020-11-23 18:19
> so I would, instead, advocate having the plugin site being more flexible in where it gets its data from, e.g. #263 as that'll fix the issue for far more than just the docker-plugin.

Nobody is stopping you from using it. Its just not implemented yet. Releases is easy you hit and endpoint then render it. Changelog is more complicated. There's no standard format so it'll require parsing and such. Just needs volunteer hours to implement

**Comment by zbynek** [comment] 2020-11-23 20:59
@pjdarton you can also manually update the releases; in https://github.com/jenkinsci/docker-plugin/releases click the "draft new release" button and type in the same markdown you would type into changelog.

Also no need to move the old changelog, a simple note like the one in https://github.com/jenkinsci/git-plugin/blob/master/CHANGELOG.adoc should be enough.

**Comment by halkeye** [comment] 2020-12-10 04:38
So all plugins will now have releases populated by update center. Release notes are still pending. But no longer be blank

**Comment by halkeye** [comment] 2020-12-10 04:39
Actually this is a dupe of #263 now so closing it

**Closed as completed by halkeye** 2020-12-10 04:39 UTC
