### ISSUE TITLE
Plugin site does not display the adopt-this-plugin label on plugin pages

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkins-infra/plugin-site#132] opened 2020-02-20 15:41 UTC
* There are 7 plugins marked with a label: https://plugins.jenkins.io/ui/search/?labels=adopt-this-plugin
* Navigating to any plugin page does not show the respective label and the adoption warning which should be displayed after #130 
* Same for deprecated. https://plugins.jenkins.io/ui/search/?labels=deprecated works, but not all plugin pages actually show it

![image](https://user-images.githubusercontent.com/3000480/74950595-a2b8b000-53ff-11ea-98b2-78960034670a.png)

![image](https://user-images.githubusercontent.com/3000480/74950653-b532e980-53ff-11ea-8f5d-6f6cd9e93b4a.png)

Looks like the static pages were not regenerated after the merge of https://github.com/jenkins-infra/update-center2/pull/342 (24 hrs ago)

**Comment by oleg-nenashev** [comment] 2020-04-06 13:43
@timja @halkeye we still hit issues with eventual consistency. Could we do something about that?

**Comment by halkeye** [comment] 2020-04-06 18:37
The problem is that by the time I take a look, its consistent for me.

Next time you see it do you want to grab a har file?

I wonder where the caching lies. Both the output and the search both use the plugin site api, so they should be the same. Its possible the nginx+azure file stuff is caching, but i'm not fully sure how it works. 

Maybe @olblak knows of something that can be tweaked?

**Comment by zbynek** [comment] 2020-11-07 17:42
@oleg-nenashev is this still an issue?

**Comment by halkeye** [comment] 2020-11-07 17:47
I *think* we fixed it with some fixes to the fastly caching rules.

**Comment by zbynek** [comment] 2020-11-11 21:24
Then maybe let's close this; if someone can reproduce some major caching delays feel free to reopen.

**Closed as completed by zbynek** 2020-11-11 21:24 UTC
Labels: bug
